version: '3.8'

services:
  # Laravel Backend + Vue Frontend (Inside Laravel)
  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app_network
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8000:8000"  # Laravel API
      - "5173:5173"  # Vue Frontend (Vite)
    command: >
        sh -c "
        composer install &&
        if [ -f resources/js/package.json ]; then npm install --prefix resources/js && npm run dev --prefix resources/js; fi &&
        php artisan key:generate &&
        until php artisan migrate --force; do echo 'Retrying migration...'; sleep 5; done &&
        php artisan db:seed --class=DatabaseSeeder || echo 'Seeding failed, skipping...' &&
        php artisan config:cache &&
        php artisan serve --host=0.0.0.0 --port=8000 &&
        composer run dev
        "

  # MariaDB Database
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: laravel
      MARIADB_USER: admin
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backup:/backup
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      interval: 5s

  # phpMyAdmin for Database Management
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:
